[package]
name = "sp-rpc"
version = "6.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate RPC primitives and utilities."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
rustc-hash = { version = "1.1.0", default-features = false }
serde = { version = "1.0.136", default-features = false, features = ["derive", "alloc"] }
sp-core = { version = "7.0.0", default-features = false, path = "../core", features = ["serde"] }
sp-std = { version = "5.0.0", default-features = false, path = "../std" }

[dev-dependencies]
serde_json = "1.0.85"

[features]
default = ["std"]
std = [
	"rustc-hash/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
]
