[package]
name = "sp-serializer"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate customizable serde serializer."
documentation = "https://docs.rs/sp-serializer"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.136", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.85", default-features = false, features = ["alloc"] }
sp-std = { version = "5.0.0", default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
	"serde/std",
	"serde_json/std",
	"sp-std/std",
]
